INSERT INTO price (id, vehicle_id, currency, price) VALUES (1, 'USD', 111.11);
INSERT INTO price (vehicle_id, currency, price) VALUES (2, 'USD', 222.22);
INSERT INTO price (vehicle_id, currency, price) VALUES (3, 'USD', 333.33);
INSERT INTO price (vehicle_id, currency, price) VALUES (4, 'USD', 400.00);
INSERT INTO price (vehicle_id, currency, price) VALUES (5, 'USD', 555,55);
INSERT INTO price (vehicle_id, currency, price) VALUES (6, 'USD', 676.7);
INSERT INTO price (vehicle_id, currency, price) VALUES (7, 'USD', 8888);
INSERT INTO price (vehicle_id, currency, price) VALUES (8, 'USD', 999);
INSERT INTO price (vehicle_id, currency, price) VALUES (9, 'USD', 1010);
INSERT INTO price (vehicle_id, currency, price) VALUES (10, 'USD', 111.11s);